### ISSUE TITLE
 Problem with loading a local library

### ISSUE THREAD

**Issue by AdrianDengusiak** [SAP/karma-ui5#367] opened 2021-11-18 15:26 UTC
Hi, 

I'm using VSC and Fiori Tools to build my projects. Currently I have a main project and a custom ui5 library, which is used in the main one. Here's the full description of the issue: https://answers.sap.com/questions/13528468/reference-library-and-karma-config.html

Basically, when I run my testsuite or unitTest pages separately, the library is loaded correctly. When I run with Karma, I get an error. 

My workspace structure is:
- zui5lib
- zui5mainproejct
(separate projects)

Comparing to the attached link, I also tried to modify my karma.conf.js a bit and I end up with:
```
module.exports` = function (config) {
	config.set({
		frameworks: ["ui5"],
		basePath: "../",
		ui5: {
			// eslint-disable-next-line sap-no-hardcoded-url
			url: "https://sapui5.hana.ondemand.com/1.71.21",
			type: "application",
			mode: "html",
			configPath: "ui5.yaml",
			paths: {
				webapp: "zui5mainproject/webapp"
			},
			testpage: "zui5mainproject/webapp/test/testsuite.qunit.html"
		},

		browsers: ["Chrome"]
	});
};
```
 In the console I see some paths are loaded from the unitTests.qunit.html, which is a part of my test suite:
```
Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58 [unitTests.qunit.html] Device API logging initialized - DEVICE'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.405800 URL prefixes set to: -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.406000   (default) : ../../resources/ -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.406100   'com/ui5/zui5mainproject' : ../../ -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) INFO: '2021-11-18 16:19:58.406199   'test/unit' : ./ -  sap.ui.ModuleSystem'

Chrome 95.0.4638.69 (Windows 10) ERROR
  Uncaught Error: failed to load 'com/ui5/zui5lib/types/CustomDateFormat.js' from ../../resources/com/ui5/zui5lib/types/CustomDateFormat.js: 404 - Not Found
  at zui5mainproject/webapp/resources/sap-ui-core.js:107:907

  Error: failed to load 'com/ui5/zui5lib/types/CustomDateFormat.js' from ../../resources/com/ui5/zui5lib/types/CustomDateFormat.js: 404 - Not Found
      at makeNestedError (zui5mainproject/webapp/resources/sap-ui-core.js:92:37)
```
I also have an entry in my ui5.yaml file, which should serve static resources from my workspace
 ```
name: fiori-tools-servestatic
          afterMiddleware: compression
          configuration:
              paths:
                  - path: /resources/com/ui5/zui5lib
                    src: c:\Users\***\Desktop\***\VSC Workspace\Common SAPUI5 Library\zui5lib\src\com\ui5\zui5lib
                    fallthrough: false

```
For some reason karma cannot resolve this route and my custom type cannot be loaded during the test execution. Each other case like launching tests outside karma, launching index.html is working fine.

How can I resolve this dependency? I feel like my ui5.yaml with servestatic middleware is not working at all.

**Comment by matz3** [comment] 2021-11-22 07:23
To me this looks similar to https://github.com/SAP/karma-ui5/issues/106
As a workaround you could try to start up a separate server and use the karma "proxies" configuration to forward the requests of the library to that server.

**Comment by AdrianDengusiak** [comment] 2021-11-22 10:10
> To me this looks similar to #106 As a workaround you could try to start up a separate server and use the karma "proxies" configuration to forward the requests of the library to that server.

Yes, it looks similar. The workaround works fine, but of course it's not a convenient solution.

**Comment by matz3** [comment] 2021-11-22 10:39
Glad to hear that it works for you. Yeah, it's not convenient, but I doubt that we will be able to improve this in the near future due to other priorities.

**Comment by matz3** [comment] 2021-11-22 10:40
Closing this issue as duplicate of #106

**Closed by matz3** 2021-11-22 10:40 UTC

**Comment by treee111** [comment] 2021-12-21 18:56
Hi @AdrianDengusiak, I have the same requirement I think. While testing a App via karma-ui5 and qunit I want to serve a library so that this library can be accessed from within the App.
Could you describe your found solution a bit more, please.
Is it like running `ui5 serve` for the library?!

**Comment by Crwing** [comment] 2022-01-11 06:34
Hi @treee111, I have one example working for me, just for your information.
At the top of karma.conf.js
```
const path = require('path')
const express = require('express') 
const serveStatic = require('serve-static')
const app = express()
app.use(serveStatic(path.join(__dirname, '../reuse_library/dist')))
app.listen(9877)
...

config.set({
    ...
    proxies: {
      '/resources/com/xxx/xxx/xxx/xxx': 'http://localhost:9877/resources/com/xxx/xxx/xxx/xxx'
    },
})
```

**Comment by AdrianDengusiak** [comment] 2022-01-11 10:19
> Hi @AdrianDengusiak, I have the same requirement I think. While testing a App via karma-ui5 and qunit I want to serve a library so that this library can be accessed from within the App. Could you describe your found solution a bit more, please. Is it like running `ui5 serve` for the library?!

Hi @treee111, sorry for a very late response.

To my karma.conf.js (config set) I just added:

```
proxies: {
	'/base/zui5lib/webapp/resources/com/ui5/zui5lib/': 'http://localhost:8080/resources/com/ui5/zui5lib'
},
```

First I run my library locally on localhost:8080. Then I launch my karma tests. The requests related to the library resources are routed to the library run on localhost.

@Crwing's solution is in fact the same operation, but resolved in a better way.

**Comment by treee111** [comment] 2022-01-25 18:15
Hi @Crwing and @AdrianDengusiak,
thank you very much for these insights! Now I understand how you managed that! 👍 

We are having a slightly other (older?!) setup. I try to integrate your input into this or need to migrate to the new suggestions by karma-ui5 for organizing QUNIT tests.

thank you very much!

karma.conf.js
```
module.exports = function(config) {
  "use strict";
  config.set({
    frameworks: ["qunit", "ui5"],
    files: [
      {
        pattern: "namespace/lib/mock/**/*",
        served: true,
        included: false
      },
      {
        pattern: "test/qunit/**/mockdata/**/*",
        served: true,
        included: false
      },
      { pattern: "karma.ui5-qunit-bootstrap.js", included: true },
      { pattern: "test/**/*qunit.js", included: true }
    ],
    ui5: {
      configPath: "ui5-karma.yaml",
      mode: "script",
      type: "application",
      config: {
        resourceRoots: {
          "namespace.app": "./base/webapp"
        },
        bindingSyntax: "complex"
      }
    },
    browsers: ["Chrome"]
  });
};
```
with this ui5-karma.yaml
```
specVersion: '2.3'
metadata:
  name: namespace.app
type: application
server:
  customMiddleware:
  - name: ui5-middleware-servestatic
    mountPath: /resources
    afterMiddleware: compression
    configuration:
      debug: true
      rootPath: "C:\\VSCode\\sapui5\\1.71.35\\resources"
```
