### ISSUE TITLE
Running karma on jenkins end up on DISCONNECTED state

### ISSUE THREAD

**Issue by IoanaIvanova** [SAP/karma-ui5#94] opened 2019-07-29 12:54 UTC
Hello, 

I have a problem running karma inside a jenkins docker container with chrome headless configuration. 
It just disconnect before the tests executed successfully. But this is not happening when I run the same karma command locally on my Mac.
This is the error that is printed: 
``` HeadlessChrome 75.0.3770 (Linux 0.0.0): Executed 0 of 27 SUCCESS (0 secs / 0 secs)
15:42:19 29 07 2019 12:42:19.384:DEBUG [HeadlessChrome 75.0.3770 (Linux 0.0.0)]: Disconnected during run, waiting 2000ms for reconnecting.
15:42:19 29 07 2019 12:42:19.384:DEBUG [HeadlessChrome 75.0.3770 (Linux 0.0.0)]: EXECUTING -> EXECUTING_DISCONNECTED
15:42:21 29 07 2019 12:42:21.386:WARN [HeadlessChrome 75.0.3770 (Linux 0.0.0)]: Disconnected (1 times)reconnect failed before timeout of 2000ms (ping timeout)
15:42:21 29 07 2019 12:42:21.386:DEBUG [HeadlessChrome 75.0.3770 (Linux 0.0.0)]: EXECUTING_DISCONNECTED -> DISCONNECTED
```

Can you tell me is there a fix or workaround for this ?

 Because I saw that many issues are created for this problem in different karma-runner projects for example [this one](https://github.com/karma-runner/karma/issues/3328)

Best Regards, 
Yoana

**Comment by matz3** [comment] 2019-07-29 13:42
As the mentioned issue is not using the `karma-ui5` plugin but describing the same symptom, I don't think that the problem is related to this project and I don't see how it can be addressed in here, sorry.

**Closed by matz3** 2019-07-29 13:42 UTC

**Comment by IoanaIvanova** [comment] 2019-07-30 10:28
But we actually use **karma-ui5** plugin for executing the tests. But  I'm not sure if this is an issue related to the karma itself or to the karma-ui5 plugin. 

@matz3 do you think that it is related to the karma itself or to something else?

These are the version of karma, karma-ui5 and karma-chrome-launcher that we are using:
```
    "karma-ui5": "^1.0.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
```

**Comment by matz3** [comment] 2019-07-30 10:44
Yes, I think it is not related to karma-ui5. I rather think this is related to the Docker environment and Chrome.
